### ISSUE TITLE
VS 2022 17.4.0 Preview 3.0: Extension v.3.6 no working

### ISSUE THREAD

**Issue by dmitryvhf** [Elders/VSE-FormatDocumentOnSave#52]
VS 2022 17.4.0 Preview 2.2: Extension v.3.5 - work
VS 2022 17.4.0 Preview 3.0: Extension v.3.5 - VS crash - fixed in v.3.6.
VS 2022 17.4.0 Preview 3.0: Extension v.3.6 - no work

Press Ctrl+S. Expected: formatting document. Actual: no formatting.

VS 2022 17.3.6: Extension v.3.6 - work ok.

**Comment by mynkow** [comment]
yes, that is correct. The extension will not be able to format any documents until Microsoft fixes the regression bug in Visual Studio. I have tried to make a workaround but that introduced more problems such as VS crashes.

We are tracking the problem here => https://github.com/Elders/VSE-FormatDocumentOnSave/issues/47
