### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by shuyih** [Elders/VSE-FormatDocumentOnSave#7]
It was working in the beginning after I installed the tool, but not it has stopped working. My visual studio 2017 version is 15.4.1

**Comment by mynkow** [comment]
I will update my VS tomorrow and test it

**Comment by mynkow** [comment]
Is v15.4.1 only available for the Enterprise SKU of Visiual Studio? The latest version I could get on the Community is 15.3

**Comment by shuyih** [comment]
possibly. I only have Enterprise SKU. If you can't find it VS Community web
site, I am sure it is not available.


Regards,
Shuyi

**Comment by mynkow** [comment]
Hello, Microsoft release 15.4.2 for Community edition. I was able to reproduce the issue described here. After a 30 min debugging and scratching my head because everything was working during debug I saw that the extention was disable for some reason. I enabled it and it just started working as expected.

Could you please check of the extention is enabled and update us?

**Comment by mynkow** [comment]
@shuyih ping

**Comment by ltlombardi** [comment]
I'm using VS 2017 15.4.4 Community and extension works ok.
